modules/Disclaimer/urls.py
from django.conf.urls import url
from .views import Index, lista_Sitiosxregion, Busqueda_Sitio, Detalle_Sitio

urlpatterns = [
    #url(r'^admin/', admin.site.urls),
    url(r'^(?P<error>[\w-]+)$', Index, name='index-disclaimer'),
    url(r'^$', Index, name='index-disclaimer'),
    url(r'^region/(?P<region>[\w-]+)/$', lista_Sitiosxregion, name='sitios_por_region'),
    url(r'^busqueda/$', Busqueda_Sitio, name='busqueda_sitio'),
    url(r'^detallesitio/(?P<pk>\d+)/$', Detalle_Sitio, name='detalle_sitio'),
]

mtz/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.views.generic import TemplateView

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    #url(r'^enrollment', include('modules.Enrollment.urls', namespace='Enrollment', app_name='Enrollment'), name="Enrollment"),
    url(r'^disclaimer/', include('modules.Disclaimer.urls', namespace='Disclaimer', app_name='Disclaimer'), name="Disclaimer"),
    url(r'^$', TemplateView.as_view(template_name='base_gral.html'), name="Inicio"),
]

# Cambia el Título en Django Admin
admin.site.site_header = 'MasTec México Admin'

modules/Disclaimer/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.

# blank= True significa si el campo requiere ingresar algún dato en los forms para su validación
# es decir, si es True no será requerido
class Sitio(models.Model):
	region = models.CharField(max_length=3, null=True)
	gerente_att = models.CharField(max_length=50, null=True, blank=True)
	coordinador_att = models.CharField(max_length=50, null=True, blank=True)
	cellowner = models.CharField(max_length=50, null=True, blank=True)
	telefono_cellowner = models.CharField(max_length=50, null=True, blank=True)
	coordinador_mastec = models.CharField(max_length=50, null=True)
	ciudad = models.CharField(max_length=50, null=True, blank=True)
	idatt_mastec = models.CharField(max_length=50, null=True, blank=True)
	id3g = models.CharField(max_length=20, null=True, blank=True)
	idgsm = models.CharField(max_length=20, null=True, blank=True)
	idlte = models.CharField(max_length=20, null=True, blank=True)
	ididen = models.CharField(max_length=20, null=True, blank=True)
	lat_decimal = models.DecimalField(max_digits=9, decimal_places=6, null=True)
	long_decimal = models.DecimalField(max_digits=9, decimal_places=6, null=True)
	nombre_sitio = models.CharField(max_length=50)
	prioridad = models.CharField(max_length=2, null=True, blank=True)
	jerarquia = models.CharField(max_length=30, null=True, blank=True)
	sitios_dependientes = models.CharField(max_length=20, null=True, blank=True)
	comentarios_att = models.TextField(null=True, blank=True)
	cluster = models.CharField(max_length=50, null=True, blank=True)
	problema_acceso = models.TextField(null=True, blank=True)
	usuario = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_sitio')
	actualizado = models.DateField(auto_now=True)
	creado = models.DateField(auto_now_add=True)

	class Meta:
		permissions = (("contra_view", "Contratista Can View"),
						("mastec_view", "Mastec Can View"),
					   )

	def __str__(self):
		return u"%s %s" % ("Sitio: ", self.nombre_sitio)

ACTIVIDAD = (
	('NOSS', 'Por Levantar'),
	('SS', 'Levantado'),
	('CWS', 'Proceso CW'),
	('CWF', 'Terminado CW'),
	('CWF', 'Entregado'),
	)

STATUS = (
	('OK', 'Activo'),
	('CA', 'Cancelado'),
	('SU', 'Suspendido'),
	)

class Status(models.Model):
	sitio = models.ForeignKey(Sitio, on_delete=models.CASCADE, related_name='status')
	ultima_actividad = models.CharField(choices=ACTIVIDAD, max_length=10)
	avance = models.PositiveSmallIntegerField(null=True, blank=True)
	status = models.CharField(choices=STATUS, max_length=30)
	creado = models.DateField(auto_now_add=True)
	usuario = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_status')

	class Meta:
		permissions = (("contra_view", "Contratista Can View"),
						("mastec_view", "Mastec Can View"),
					   )

	def __str__(self):
		return u"%s" % (self.sitio)

class Levantamiento(models.Model):
	sitio = models.ForeignKey(Sitio,on_delete=models.CASCADE, related_name='levantamientos')
	ss_sem_att = models.PositiveSmallIntegerField(null=True, blank=True)
	ss_programado = models.DateField(null=True, blank=True)
	ss_real = models.DateField(null=True, blank=True)
	ss_hechox = models.CharField(max_length=50, null=True, blank=True)
	ss_nota = models.TextField(null=True, blank=True)
	ss_recibido = models.DateField(null=True, blank=True)
	ss_validacion = models.DateField(null=True, blank=True)
	creado = models.DateField(auto_now_add=True)
	usuario = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_ss')

	class Meta:
		permissions = (("contra_view", "Contratista Can View"),
						("mastec_view", "Mastec Can View"),
					   )

	def __str__(self):
		return u"%s" % (self.sitio)

SUPERVISOR = (
		('ALS', 'Alan Santana'),
		('AS', 'Antonio Salazar'),
		('AB', 'Arturo Bautista'),
		('FO', 'Fabián Olan'),
		('FJ', 'Francisco Juárez'),
		('GJ', 'Gerardo Jiménez'),
		('JG', 'Jaime García'),
		('JP', 'Juan Pablo Flores'),
		('LG', 'Luis Gutierrez'),
		('LD', 'Lino De La Rosa'),
		('ME', 'Martín Elías'),
		('MS', 'Miguel Salgado'),
		('OL', 'Oscar López'),
		('OM', 'Oscar Marín'),
		('PQ', 'Pablo Quezada'),
		('PS', 'Pedro Santiago'),
	)

# Lista de proveedores para campo choices de class Mantenimiento y 
# class Profile
PROVEEDOR = (
		('AP', 'Ancla Proyectos'),
		('CM', 'Color Machines'),
		('DH', 'David Hernández'),
		('EKSA', 'ECCASA'),
		('ETL', 'ECOTEL'),
		('FS', 'Franco & Soto'),
		('FD', 'Freddy'),
		('GICOM', 'Grupo ICOM'),
		('GIP', 'Grupo IPE'),
		('GVI', 'Grupo VALBRI'),
		('GST', 'Grupo SET'),
		('IR', 'IRed'),
		('JAVCRUZ', 'Javier De La Cruz'),
		('JAVJ', 'Javier Jiménez'),
		('JJ', 'Juan Jesús'),
		('MC', 'Macario Hernández'),
		('MQ', 'Maqueda'),
		('VK', 'Ve-Ca'),
		('VI', 'Viadeza'),
		('IR', 'IRed'),
	)

class Mantenimiento(models.Model):
	sitio = models.ForeignKey(Sitio,on_delete=models.CASCADE, related_name='mnto')
	proveedor = models.CharField(choices=PROVEEDOR, max_length=50, null=True, blank=True)
	supervisor = models.CharField(choices=SUPERVISOR, max_length=50, null=True, blank=True)
	cuadrilla = models.CharField(max_length=50, null=True, blank=True)
	cos_sem_att = models.PositiveSmallIntegerField(null=True, blank=True)
	cos_programado =  models.DateField(null=True, blank=True)
	cos_real = models.DateField(null=True, blank=True)
	cof_sem_att = models.PositiveSmallIntegerField(null=True, blank=True)
	cof_programado = models.DateField(null=True, blank=True)
	cof_real = models.DateField(null=True, blank=True)
	fech_odk = models.DateField(null=True, blank=True)
	nota_sitio = models.TextField(null=True, blank=True)
	creado = models.DateField(auto_now_add=True)
	usuario = models.ForeignKey(User,on_delete=models.CASCADE, related_name='users_mnt')

	class Meta:
		permissions = (("contra_view", "Contratista Can View"),
						("mastec_view", "Mastec Can View"),
					   )

	def __str__(self):
		return u"%s" % (self.sitio)

class Volumetrico(models.Model):
	sitio = models.ForeignKey(Sitio,on_delete=models.CASCADE, related_name='sitio_presupto')
	volPre_recepcion = models.DateField(null=True, blank=True)
	volPre_monto = models.DecimalField(max_digits=9, decimal_places=2, blank=True, default=0.0)
	vol_po_solitada = models.DateField(null=True, blank=True)
	vol_po_monto = models.DecimalField(max_digits=9, decimal_places=2, blank=True)
	vol_final_recibido = models.DateField(null=True, blank=True)
	vol_final_vobo = models.CharField(choices=SUPERVISOR, max_length=50, null=True, blank=True)
	vol_envio_att = models.DateField(null=True, blank=True)
	vol_monto_venta = models.DecimalField(max_digits=9, decimal_places=2, blank=True)
	vol_valida_att = models.DateField(null=True, blank=True)
	vol_creado = models.DateField(auto_now_add=True)
	usuario = models.ForeignKey(User,on_delete=models.CASCADE, related_name='user_presupto')

	class Meta:
		permissions = (("contra_view", "Contratista Can View"),
						("mastec_view", "Mastec Can View"),
					   )

	def __str__(self):
		return u"%s" % (self.sitio)

class Profile(models.Model):
	usuario = models.OneToOneField(User,on_delete=models.CASCADE, related_name='profile')
	es_contrata = models.BooleanField(default=True)
	contrata_view = models.BooleanField(default=False)
	mastec_admin = models.BooleanField(default=False)
	proveedor = models.CharField(choices=PROVEEDOR, max_length=50, null=True, blank=True)


	class Meta:
		permissions = (("contra_view", "Contratista Can View"),
						("mastec_view", "Mastec Can View"),
					   )

# ToDo 
"""
¿¿¿¿¿¿¿Control de PO's de contratistas??????
¿¿¿¿¿¿¿Agregar a modelo volumétricos?????




para checar permisos de usuarios en View

if request.user.has_perm('app_name.can_add_cost_price')

ó se puede usar:

@login_required
@permission_required('polls.can_vote', raise_exception=True)
def my_view(request):
..............


Si es que en Models:

class Meta:
        permissions = (
            ("can_add_cost_price", "Can add cost price"),
        )


31-MAR-2017: Completar lista de proveedores


"""

modules/Disclaimer/forms.py
from django import forms

class BusquedaForm(forms.Form):
	q = forms.CharField(label = "Sitio", max_length=12)

modules/Disclaimer/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from .models import Sitio, Status, Mantenimiento, Volumetrico
from django.db.models import Q
from .forms import BusquedaForm
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


# Create your views here.

# Vista para dashboard Disclaimer
# Calcula número total de sitios, iniciados, terminados, en proceso, suspendidos
# Por región
def Index(request, error=False):
	sitioxRegion = []
	print("Si estoy adentro de Index Disclaimer:")
	# Sitios Asignados Por Región
	sitioxRegion.append(Sitio.objects.filter(coordinador_mastec__exact='Oscar').count())
	sitioxRegion.append(Sitio.objects.filter(coordinador_mastec__exact='Luis Gutierrez').count())
	sitioxRegion.append(Sitio.objects.filter(coordinador_mastec__exact='Lino De La Rosa').count())
	sitioxRegion.append(Sitio.objects.filter(coordinador_mastec__exact='Alfonso Merlos').count())

	# ToDo Sitios iniciados
	# ToDo Sitios Terminados
	# ToDo Sitios En Proceso
	# ToDo Sitios Entregados

	form = BusquedaForm()
	elerror = error

	return render(request,'Disclaimer/index_disclaimer.html',{'sitioxRegion': sitioxRegion, 'form': form, 'elerror': elerror})


# view que lista todos los sitios de una región (Guerrero, Morelos, Tabasco, Yucatán)
# utiliza template Disclaimer/sitiosxregion_disclaimer.html
def lista_Sitiosxregion(request, region):

	if region == "Guerrero":
		coord_mastec='Oscar'
	elif region =="Morelos":
		coord_mastec='Luis Gutierrez'
	elif region =="Tabasco":
		coord_mastec='Lino De La Rosa'
	elif region =="Yucatan":
		coord_mastec='Alfonso Merlos'

	# En Queryset sólo están los campos
	sitios_lista = Sitio.objects.only('idatt_mastec','nombre_sitio','region','coordinador_mastec','cellowner').filter(coordinador_mastec__exact=coord_mastec)

	paginator = Paginator(sitios_lista, 5)

	page = request.GET.get('page')

	try:
		sitios = paginator.page(page)
	except PageNotAnInteger:
		# If page is not an integer, deliver first page.
		sitios = paginator.page(1)
	except EmptyPage:
		# If page is out of range (e.g. 9999), deliver last page of results.
		sitios = paginator.page(paginator.num_pages)

	form = BusquedaForm()

	return render(request,'Disclaimer/sitiosxregion_disclaimer.html',{'sitios': sitios, 'region': region, 'form': form})

# Búsqueda de Sitios
# recibe párametro de formulario en barra de navegación de template base.html
def Busqueda_Sitio(request):

	if request.method == 'POST':
		form = BusquedaForm(request.POST)
		if form.is_valid():
			q = form.cleaned_data['q']

			sitios = Sitio.objects.filter(Q(nombre_sitio__unaccent__icontains=q)|
											Q(id3g__icontains=q)|
											Q(idgsm__icontains=q)|
											Q(idlte__icontains=q)|
											Q(idgsm__icontains=q)|
											Q(ididen__icontains=q)
								)

			#print("String recibido: " + q)

			for sitio in sitios:
				print("sitio PK: " + str(sitio.pk))
			
			return render(request, 'Disclaimer/sitiosxregion_disclaimer.html', {'sitios':sitios, 'form': form})

		else:
			elerror = True
			return redirect('Disclaimer:index-disclaimer', elerror)
	else:
		form = BusquedaForm()
		return render(request, 'Disclaimer/index_disclaimer.html', {'form': form})


def Detalle_Sitio(request,pk):
	sitio = Sitio.objects.get(pk=pk)
	print("dentro Detalle_Sitio pk "+pk)
	status = Status.objects.get(pk=pk)
	mantenimiento = Mantenimiento.objects.get(pk=pk)

	print("sitio NAME: " + str(sitio.nombre_sitio))

	form = BusquedaForm()

	return render(request,'Disclaimer/detallesitio_disclaimer.html',{'sitio': sitio, 'status': status, 
																'mantenimiento': mantenimiento, 'form': form})

templates/Disclaimer/busquedasitio_disclaimer - copia.html
{%extends 'base.html'%}
{%load static%}

{%block 'title'%}<title>MasTec Disclaimer Búsqueda De Sitio</title>{%endblock%}


{%block 'content'%}

	<div class="row"><!-- row2 Dashboard style="margin-top: 48px;"-->
      
      <ol class="breadcrumb" style="margin-top: 58px;">
        <li><a href="{% url 'Inicio' %}">Inicio</a></li>
        <li><a href="{% url 'Disclaimer:index-disclaimer' %}">Disclaimer</a></li>
        <li class="active">{{region}}</li>
      </ol>

      <h1 class="text-center">Proyecto Disclaimer. Sitios Región {{region}}</h1>

      <div class="table-responsive"><!-- table-responsive -->
            <table class="table table-striped ">
              <thead>
                <tr>
                  <th>#</th>
                  <th>Site Id</th>
                  <th>Site Name</th>
                  <th>Región</th>
                  <th>Coord. MasTec</th>
                  <th>CellOwner</th>
                </tr>
              </thead>
              <tbody>
                
                {% for sitio in sitios %}
                  <tr>
                    <td>{{forloop.counter}}</td>
                    <td>{{sitio.idatt_mastec}}</td>
                    <td>{{sitio.nombre_sitio}}</td>
                    <td>{{sitio.region}}</td>
                    <td>{{sitio.coordinador_mastec}}</td>
                    <td>{{sitio.cellowner}}</td>
                  </tr>
                {% endfor %}
              </tbody>
           </table>
      </div><!-- /table-responsive -->
      
      <div class="pagination">
        <span class="step-links">
          {% if sitios.has_previous %}
              <a href="?page={{ sitios.previous_page_number }}">Previa</a>
          {% endif %}

          <span class="current">
              Página {{ sitios.number }} De {{ sitios.paginator.num_pages }}.
          </span>

          {% if sitios.has_next %}
              <a href="?page={{ sitios.next_page_number }}">Siguiente</a>
          {% endif %}
        </span>
      </div>


  </div><!-- /row2 Dashboard-->


{%endblock%} <!-- Termina bloque content -->

templates/Disclaimer/detallesitio_disclaimer.html
{%extends '../base.html'%}
{%load static%}

{%block 'title'%}<title>MasTec Disclaimer Sitio {{sitio.nombre_sitio}} </title>{%endblock%}


{%block 'content'%}
detallesitio_disclaimer.html
	<div class="row"><!-- row2 Dashboard style="margin-top: 48px;"-->
      
      <ol class="breadcrumb" style="margin-top: 58px;">
        <li><a href="{% url 'Inicio' %}">Inicio</a></li>
        <li><a href="{% url 'Disclaimer:index-disclaimer' %}">Disclaimer</a></li>
        <li class="active">Sitio 
          {% if status.idatt_mastec or status.idatt_mastec == "0" %}
            {{sitio.idatt_mastec}} 
          {% endif %}
          {{sitio.nombre_sitio}}
        </li>
      </ol>

      <h1 class="text-center">
        {% if status.idatt_mastec or status.idatt_mastec == "0" %}
            {{sitio.idatt_mastec}} 
          {% endif %}
           {{sitio.id3g}} {{sitio.nombre_sitio}}</h1>
  
    <h3 class="text-left"><span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span> ID's</h3>
      <div class="table-responsive"><!-- table-responsive -->
            <table class="table table-striped ">
              <thead>
                <tr>
                  <th>IDATT</th>
                  <th>ID3G</th>
                  <th>IDGSM</th>
                  <th>IDLTE</th>
                  <th>IDiDEN</th>
                  <th>SITE NAME</th>
                </tr>
              </thead>
              <tbody>
                  <tr>
                    <td>
                        {% if status.idatt_mastec or status.idatt_mastec == "0" %}
                          {{sitio.idatt_mastec}} 
                        {% endif %}
                    </td>
                    <td>{{sitio.id3g}}</td>
                    <td>{{sitio.idgsm}}</td>
                    <td>{{sitio.idlte}}</td>
                    <td>{{sitio.ididen}}</td>
                    <td>{{sitio.nombre_sitio}}</td>
                  </tr>
              </tbody>
           </table>
      </div><!-- /table-responsive -->  





  <h3 class="text-left"><span class="glyphicon glyphicon-plus" aria-hidden="true"></span> Datos Generales</h3>
  <div class="table-responsive"><!-- table-responsive -->
            <table class="table table-striped ">
              <thead>
                <tr>
                  <th>Región</th>
                  <th>Prioridad</th>
                  <th>Latitud</th>
                  <th>Longitud</th>
                  <th>CellOwner</th>
                  <th>Cell Owner Tel</th>
                  <th>Comentario ATT</th>
                </tr>
              </thead>
              <tbody>
                  <tr>
                    <td>{{sitio.region}}</td>
                    <td>{{sitio.prioridad}}</td>
                    <td>
                      <a href="http://maps.google.com/?q={{sitio.lat_decimal}},{{sitio.long_decimal}}" target="_blank">
                        {{sitio.lat_decimal}}
                      </a>
                    </td>
                    <td>
                      <a href="http://maps.google.com/?q={{sitio.lat_decimal}},{{sitio.long_decimal}}" target="_blank">
                        {{sitio.long_decimal}}
                      </a>
                    </td>
                    <td>{{sitio.cellowner}}</td>
                    <td>{{sitio.telefono_cellowner}}</td>
                    <td>{{sitio.comentarios_att}}</td>
                  </tr>
              </tbody>
           </table>
      </div><!-- /table-responsive -->



      
      <p>
        {% if status.avance %}
          <b>Avance:</b> {{status.avance}}% </p>
        {% else %}
          <b>Avance:</b> 0 % </p>
        {% endif %}

      <div class="progress">
                      <div class="progress-bar progress-bar-success" style="width: {{status.avance}}%">
                        <span class="sr-only">{{status.avance}}% Complete (success)</span>
                      </div>
      </div>
      <p><b>Proveedor:</b> {{mantenimiento.get_proveedor_display}} </p> 


      Ver en <a href="http://maps.google.com/?q={{sitio.lat_decimal}},{{sitio.long_decimal}}" target="_blank"> <span class="glyphicon glyphicon-pushpin" aria-hidden="true"></span> Google Maps</a>

  <div class="panel-group" id="accordion" role="tablist" aria-multiselectable="true">
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingOne">
      <h4 class="panel-title">
        <a role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          1.- Status:
        </a>
      </h4>
    </div>
    <div id="collapseOne" class="panel-collapse collapse " role="tabpanel" aria-labelledby="headingOne">
      <div class="panel-body">
        <p><b>Ultima Actividad:</b> {{status.ultima_actividad}} </p> 
        <p><b>Status:</b> 
            {% if status.get_status_display == 'Cancelado' %}

            {% else %}
              {{status.get_status_display}}
            {% endif %}    
        </p> 
        <p>
          {% if status.avance %}
            <b>Avance:</b> {{status.avance}}%
          {% else %}
            <b>Avance:</b> 0 % 
          {% endif %}
        </p>
        <p><b>Contratista:</b> {{mantenimiento.get_proveedor_display}} </p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading panel-primary" role="tab" id="headingTwo">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          2.- Levantamiento:
        </a>
      </h4>
    </div>
    <div id="collapseTwo" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingTwo">
      <div class="panel-body">
        <p><b>Semana Programada AT&T:</b> {{status.ultima_actividad}} </p> 
        <p><b>Fecha Programada AT&T:</b> {{status.get_status_display}} </p>
        <p><b>Fecha Ejecución:</b> {{status.avance}}% </p>
        <p><b>Levantado Por:</b> {{status.avance}}% </p>
        <p><b>Nota:</b> {{status.avance}}% </p>
        <p><b>Recibido Por MasTec:</b> {{status.avance}}% </p>
        <p><b>Validado por AT&T:</b> {{status.avance}}% </p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingThree">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
          3.- Programa De Obra
        </a>
      </h4>
    </div>
    <div id="collapseThree" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingThree">
      <div class="panel-body">
       <p><b>Proveedor:</b> {{mantenimiento.get_proveedor_display}} </p> 
        <p><b>Supervisor:</b> {{mantenimiento.get_supervisor_display}} </p>
        <p><b>Cuadrilla:</b> {{mantenimiento.cuadrilla}}</p>
        <p><b>Semana Inicio Programado AT&T:</b> {{mantenimiento.cos_sem_att}}% </p>
        <p><b>Inicio Programado AT&T:</b> {{mantenimiento.cos_programado}}% </p>
        <p><b>Inicio Real:</b> {{mantenimiento.cos_real}}% </p>
        <p><b>Semana Fin Programado:</b> {{mantenimiento.cof_sem_att}}% </p>
        <p><b>Fecha Fin Programado:</b> {{mantenimiento.cof_programado}}% </p>
        <p><b>Fecha Fin Real:</b> {{mantenimiento.real}}% </p>
      </div>
    </div>
  </div>
  <div class="panel panel-default">
    <div class="panel-heading" role="tab" id="headingFour">
      <h4 class="panel-title">
        <a class="collapsed" role="button" data-toggle="collapse" data-parent="#accordion" href="#collapseFour" aria-expanded="false" aria-controls="collapseFour">
          4.- Volumétrico:
        </a>
      </h4>
    </div>
    <div id="collapseFour" class="panel-collapse collapse" role="tabpanel" aria-labelledby="headingFour">
      <div class="panel-body">
        Anim pariatur cliche reprehenderit, enim eiusmod high life accusamus terry richardson ad squid. 3 wolf moon officia aute, non cupidatat skateboard dolor brunch. Food truck quinoa nesciunt laborum eiusmod. Brunch 3 wolf moon tempor, sunt aliqua put a bird on it squid single-origin coffee nulla assumenda shoreditch et. Nihil anim keffiyeh helvetica, craft beer labore wes anderson cred nesciunt sapiente ea proident. Ad vegan excepteur butcher vice lomo. Leggings occaecat craft beer farm-to-table, raw denim aesthetic synth nesciunt you probably haven't heard of them accusamus labore sustainable VHS.
      </div>
    </div>
  </div>
</div>

  </div><!-- /row2 Dashboard-->

  

{%endblock%} <!-- Termina bloque content -->

templates/Disclaimer/sitiosxregion_disclaimer.html
{%extends 'base.html'%}
{%load static%}

{%block 'title'%}<title>MasTec Disclaimer Sitios Región {{region}}</title>{%endblock%}


{%block 'content'%}

	<div class="row"><!-- row2 Dashboard style="margin-top: 48px;"-->
      
      <ol class="breadcrumb" style="margin-top: 58px;">
        <li><a href="{% url 'Inicio' %}">Inicio</a></li>
        <li><a href="{% url 'Disclaimer:index-disclaimer' %}">Disclaimer</a></li>
        <li class="active">{{region}}</li>
      </ol>

      <h1 class="text-center">Proyecto Disclaimer. Sitios Región {{region}}</h1>

      <div class="table-responsive"><!-- table-responsive -->
            <table class="table table-striped ">
              <thead>
                <tr>
                  <th>#</th>
                  <th>IDATT</th>
                  <th>ID3G</th>
                  <th>IDGSM</th>
                  <th>IDLTE</th>
                  <th>IDiDEN</th>
                  <th>SITE NAME</th>
                </tr>
              </thead>
              <tbody>
                
                {% for sitio in sitios %}
                  <tr>
                    <td>{{forloop.counter}}</td>
                    <td>
                      <a href="{% url 'Disclaimer:detalle_sitio' sitio.pk %}">
                        {% if sitio.idatt_mastec %}
                          {{sitio.idatt_mastec}}
                        {% else %}
                        {% endif %} 
                      </a>
                    </td>
                    <td>
                        {% if sitio.id3g %}
                          {{sitio.id3g}}
                        {% else %}
                        {% endif %} 
                    </td>
                    <td>
                        {% if sitio.idgsm %}
                          {{sitio.idgsm}}
                        {% else %}
                        {% endif %} 
                    </td>
                    <td>
                        {% if sitio.idlte %}
                          {{sitio.idlte}}
                        {% else %}
                        {% endif %} 
                    </td>
                    <td>
                        {% if sitio.ididen %}
                          {{sitio.ididen}}
                        {% else %}
                        {% endif %} 
                    </td>
                    <td>
                      <a href="{% url 'Disclaimer:detalle_sitio' sitio.pk %}">
                        {% if sitio.nombre_sitio %}
                          {{sitio.nombre_sitio}}
                        {% else %}
                        {% endif %} 
                      </a>
                    </td>
                  </tr>
                {% endfor %}
              </tbody>
           </table>
      </div><!-- /table-responsive -->
      
      <div class="pagination">
        <span class="step-links">
          {% if sitios.has_previous %}
              <a href="?page={{ sitios.previous_page_number }}">Previa</a>
          {% endif %}

          <span class="current">
              Página {{ sitios.number }} De {{ sitios.paginator.num_pages }}.
          </span>

          {% if sitios.has_next %}
              <a href="?page={{ sitios.next_page_number }}">Siguiente</a>
          {% endif %}
        </span>
      </div>


  </div><!-- /row2 Dashboard-->


{%endblock%} <!-- Termina bloque content -->